public enum RequestOption {
    PLAYLIST_ITEMS,
    ADD_ITEM,
    DELETE_ITEM,
    CREATE_PLAYLIST,
    USER_ID,
    PLAYLIST_ID,
    ALL_FAV_SONGS_COUNT,
    ALL_CLONED_SONGS_COUNT,
    ALL_PLAYLISTS_COUNT,
    FAV_PLAYLIST_ITEMS
}
